[tools]
node = "24"
python = "3.14"
ruby = "3.4.9"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby"]

[settings.node]
compile = false
corepack = true

[settings.python]
uv_venv_auto = "create|source"

[settings.ruby]
compile = false
